# Generated by Django 6.0.5 on 2026-06-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('open', 'open'), ('paid', 'paid'), ('cancelled', 'cancelled')], default='draft', max_length=10),
        ),
    ]
