# Generated by Django 6.0.5 on 2026-06-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('paid', 'paid')], default='open', max_length=10),
        ),
    ]
